site_name: smart-settings
repo_url: https://github.com/ZiadMansourM/settings
nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true